#pragma config(Motor,  port2,           leftDriver,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightDriver,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
	{
	if(vexRT[Btn7U] == 1)
		{
		startMotor(leftDriver, 127);
		startMotor(rightDriver, 127);
		wait(1.8);
		stopMotor(leftDriver);
		stopMotor(rightDriver);
		}
	}
}
