#pragma config(Motor,  port2,           leftDriver,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           rightpicker,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           lefttrans,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Dropper,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           righttrans,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftpicker,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          rightDriver,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
	{
	if(vexRT[Btn7L] == 1)
		{
		startMotor(leftDriver, 127);
		startMotor(rightDriver, 120);
		wait(1.7);
		stopMotor(leftDriver);
		stopMotor(rightDriver);
		startMotor(rightpicker, 127);
		startMotor(leftpicker, 127);
		startMotor(lefttrans, 127);
		startMotor(righttrans, 127);
		wait(2);
		stopMotor(leftpicker);
		stopMotor(rightpicker);
		stopMotor(lefttrans);
		stopMotor(righttrans);
		startMotor(leftDriver, 127);
		startMotor(rightDriver, 120);
		wait(0.6);
		stopMotor(leftDriver);
		stopMotor(rightDriver);
		}
	}
}
