#pragma config(Motor,  port2,           leftDriver,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           rightpicker,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           lefttrans,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Dropper,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           righttrans,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftpicker,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          rightDriver,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
while(true)
{
if(vexRT[Btn6D] == 1)
{
motor[leftDriver] = -100;
motor[rightDriver] = 100;
}
else if(vexRT[Btn5D] == 1)
{
motor[leftDriver] = 100;
motor[rightDriver] = -100;
}
else
{
if(vexRT[Btn8U] == 1)
{
motor[leftpicker] = 127;
motor[rightpicker] = 127;
motor[lefttrans] = 127;
motor[righttrans] = 127;
}
else if(vexRT[Btn8D] == 1)
{
motor[leftpicker] = -127;
motor[rightpicker] = -127;
motor[lefttrans] = -127;
motor[righttrans] = -127;
}
else
{
motor[leftDriver] = -vexRT[Ch2];
motor[rightDriver] = -vexRT[Ch3];
}
}
}
}

