#pragma config(Motor,  motor2,          qween,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         king,          tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
while(Btn7L == 1)
{
startMotor(king, -127);
startMotor(qween, -127);
wait(5);
stopMotor(king);
stopMotor(qween);
wait(5)

startMotor(king, -127);
startMotor(qween, -127);
wait(1);
stopMotor(king);
stopMotor(qween);
wait(1);

startMotor(king, -127);
startMotor(qween, -127);
wait(1);
stopMotor(king);
stopMotor(qween);
wait(2);
startMotor(king, -127);
startMotor(qween, -127);
wait(8);
stopMotor(king);
stopMotor(qween);
}

while(Btn7L == 0)
{
if(vexRT[Btn6D] == 1)
{
motor[qween] = -100;
motor[king] = 100;
}
else if(vexRT[Btn5D] == 1)
{
motor[qween] = 100;
motor[king] = -100;
}
else
{
motor[qween] = -vexRT[Ch2];
motor[king] = -vexRT[Ch3];
}
}
}
}
